In [ ]:
import pandas as pd

from google.colab import files

chukyo = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Chukyo.csv')
higas = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Higashisurugawan.csv')
kyushu = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Kyushu.csv')
tokyo = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Tokyo.csv')
sample_s = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/sample_submission.csv')
data_s = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Data_Specification.csv')
test_f = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/test.csv')
chukyo_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Chukyo_zone_feature_area.csv')
higas_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Higashisurugawan_zone_feature_area.csv')
kyushu_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Kyushu_zone_feature_area.csv')
tokyo_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Tokyo_zone_feature_area.csv')
kinki_zone_features = pd.read_csv('/content/drive/MyDrive/IntegratedDB_DoNotTouch/Kinki_zone_feature_area.csv')

chukyo_copy = chukyo.copy()
higas_copy = higas.copy()
kyushu_copy = kyushu.copy()
tokyo_copy = tokyo.copy()
sample_copy = sample_s.copy()
data_copy = data_s.copy()
test_copy = test_f.copy()
chukyo_zone_features_copy = chukyo_zone_features.copy()
higas_zone_features_copy = higas_zone_features.copy()
kyushu_zone_features_copy = kyushu_zone_features.copy()
tokyo_zone_features_copy = tokyo_zone_features.copy()
kinki_zone_features_copy = kinki_zone_features.copy()

import pandas as pd

df = pd.DataFrame(data_copy)

cities = ['Tokyo', 'Chukyo']
labels = ['Occupation', 'Trip Type']

tokyo_occupation = df[(df['City'] == cities[0]) & (df['Type'] == labels[0])]
tokyo_trip = df[(df['City'] == cities[0]) & (df['Type'] == labels[1])]

chukyo_occupation = df[(df['City'] == cities[1]) & (df['Type'] == labels[0])]
chukyo_trip = df[(df['City'] == cities[1]) & (df['Type'] == labels[1])]

occupation = df[(df['Type'] == labels[0])]
trip = df[(df['Type'] == labels[1])]

# Get unique values in the 'Category' column and assign unique integers
occupation['Occupation_Encoded'] = pd.factorize(occupation['Description'])[0]
trip['Trip_Encoded'] = pd.factorize(trip['Description'])[0]

occupation = occupation.drop('City', axis=1)
occupation = occupation.drop('Type', axis=1)
occupation = occupation.drop('Code', axis=1)

trip = trip.drop('Code', axis=1)
trip = trip.drop('City', axis=1)
trip = trip.drop('Type', axis=1)

tokyo_occupation.rename(columns={'Code': 'Occupation'}, inplace=True)
tokyo_trip.rename(columns={'Code': 'Trip_type'}, inplace=True)

chukyo_occupation.rename(columns={'Code': 'Occupation'}, inplace=True)
chukyo_trip.rename(columns={'Code': 'Trip_type'}, inplace=True)

# Convert to int
tokyo_copy['Occupation'] = tokyo_copy['Occupation'].astype(int)
chukyo_copy['Occupation'] = chukyo_copy['Occupation'].astype(int)

tokyo_copy['Trip_type'] = tokyo_copy['Trip_type'].astype(int)
chukyo_copy['Trip_type'] = chukyo_copy['Trip_type'].astype(int)

tokyo_occupation['Occupation'] = tokyo_occupation['Occupation'].astype(int)
chukyo_occupation['Occupation'] = chukyo_occupation['Occupation'].astype(int)

tokyo_trip['Trip_type'] = tokyo_trip['Trip_type'].astype(int)
chukyo_trip['Trip_type'] = chukyo_trip['Trip_type'].astype(int)

tokyo_modified = pd.merge(tokyo_copy, tokyo_occupation, on='Occupation', how='inner')
tokyo_modified = tokyo_modified.drop('Occupation', axis=1)
tokyo_modified = tokyo_modified.drop('Type', axis=1)
tokyo_modified = tokyo_modified.drop('City', axis=1)
tokyo_modified.rename(columns={'Description': 'Occupation'}, inplace=True)

chukyo_modified = pd.merge(chukyo_copy, chukyo_occupation, on='Occupation', how='inner')
chukyo_modified = chukyo_modified.drop('Occupation', axis=1)
chukyo_modified = chukyo_modified.drop('Type', axis=1)
chukyo_modified = chukyo_modified.drop('City', axis=1)
chukyo_modified.rename(columns={'Description': 'Occupation'}, inplace=True)

tokyo_modified = pd.merge(tokyo_modified, tokyo_trip, on='Trip_type', how='inner')
tokyo_modified = tokyo_modified.drop('Trip_type', axis=1)
tokyo_modified.rename(columns={'Description': 'Trip_type'}, inplace=True)
tokyo_modified = tokyo_modified.drop('Type', axis=1)

chukyo_modified = pd.merge(chukyo_modified, chukyo_trip, on='Trip_type', how='inner')
chukyo_modified = chukyo_modified.drop('Trip_type', axis=1)
chukyo_modified.rename(columns={'Description': 'Trip_type'}, inplace=True)
chukyo_modified = chukyo_modified.drop('Type', axis=1)

tokyo_features = tokyo_zone_features_copy.rename(columns={'ZONE_ID': 'Origin'})
chukyo_features = chukyo_zone_features_copy.rename(columns={'ZONE_ID': 'Origin'})

tokyo_modified = pd.merge(tokyo_modified, tokyo_features, on='Origin', how='inner')
chukyo_modified = pd.merge(chukyo_modified, chukyo_features, on='Origin', how='inner')

tokyo_modified.rename(columns={'T000918002': 'Number of business establishments (secondary sector of industry)', 'T000918006' : 'Number of employees (secondary sector of industry)', 'T000918021' : 'Number of business establishments (tertiary sector of industry)', 'T000918025' : 'Number of employees (tertiary sector of industry)', 'T000847001' : 'Night Population' }, inplace=True)
chukyo_modified.rename(columns={'T000918002': 'Number of business establishments (secondary sector of industry)', 'T000918006' : 'Number of employees (secondary sector of industry)', 'T000918021' : 'Number of business establishments (tertiary sector of industry)', 'T000918025' : 'Number of employees (tertiary sector of industry)', 'T000847001' : 'Night Population' }, inplace=True)

occupation_rename = occupation.rename(columns={'Description': 'Occupation'})

tokyo_modified = pd.merge(tokyo_modified, occupation_rename, on='Occupation', how='inner')
chukyo_modified = pd.merge(chukyo_modified, occupation_rename, on='Occupation', how='inner')

trip_rename = trip.rename(columns={'Description': 'Trip_type'})

tokyo_modified = pd.merge(tokyo_modified, trip_rename, on='Trip_type', how='inner')
chukyo_modified = pd.merge(chukyo_modified, trip_rename, on='Trip_type', how='inner')

chukyo_modified = chukyo_modified.drop_duplicates()

*Reading Files from the drive and creating a copy of each DS*

In [ ]:
#reading the text file
data_path = '/content/drive/MyDrive/IntegratedDB_DoNotTouch/feature_description.txt'

with open(data_path) as fid:
    data = "Dummy String"
    while data:
        data = fid.readline()
        # print(data)

In [ ]:
chukyo_zone_features_copy['Destination_New'] =  range(0, 1009)

In [ ]:
czp = chukyo_zone_features_copy[['Destination_New', 'ZONE_ID']]
czp.rename(columns={'ZONE_ID': 'Destination'}, inplace=True)

<ipython-input-6-70193c7c7148>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  czp.rename(columns={'ZONE_ID': 'Destination'}, inplace=True)


In [ ]:
czp =czp.drop_duplicates()

In [ ]:
chukyo_modified = pd.merge(chukyo_modified, czp, on='Destination', how='inner')
len(chukyo_modified)

205435

In [ ]:
chukyo_modified['Departure_time'] = pd.to_datetime(chukyo_modified['Departure_time'])
chukyo_modified['Departure_time'] = chukyo_modified['Departure_time'].dt.time

In [ ]:
chukyo_modified = chukyo_modified.sort_values(by='Departure_time', ascending=True)

In [ ]:
# Convert the 'TimeOnly' column to a string with a custom format
chukyo_modified['Departure_time'] = chukyo_modified['Departure_time'].apply(lambda x: x.strftime('%H'))

In [ ]:
# Creating training and testing sets.
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

chukyo_df = pd.DataFrame(chukyo_modified)

# X = pd.DataFrame(data.data, columns=data.feature_names)
# y = (data.target == 0).astype(int)  # Binary classification: Setosa vs. Not Setosa
result = chukyo_df['Destination_New'].values
input = chukyo_df.drop('Destination_New', axis=1, inplace=False)

In [ ]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(chukyo_df, result, test_size=0.2, random_state=42)

Feature Engineering.

In [ ]:
x_train_dropped = X_train.drop(['Occupation', 'City', 'Trip_type', 'Destination', 'Destination_New'], axis=1)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, chi2, f_classif, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import mutual_info_classif

# 1. Correlation Analysis
# correlation_matrix = np.corrcoef(x_train_dropped, rowvar=False)
# highly_correlated_features = np.where(np.abs(correlation_matrix) > 0.8)

# 2. Univariate Feature Selection
k_best = 5  # You can adjust this based on the number of features you want to select
selector = SelectKBest(score_func=f_classif, k=k_best)
X_train_univariate = selector.fit_transform(x_train_dropped, y_train)
selected_features_univariate = np.where(selector.get_support())[0]
print("Selected features using Univariate Feature Selection:", selected_features_univariate)

# 3. Recursive Feature Elimination (RFE)
model = RandomForestClassifier(n_estimators=10)
rfe_selector = RFE(model, n_features_to_select=k_best)
X_train_rfe = rfe_selector.fit_transform(x_train_dropped, y_train)
selected_features_rfe = np.where(rfe_selector.support_)[0]
print("Selected features using Recursive Feature Elimination (RFE):", selected_features_rfe)

# 4. Tree-based Methods
tree_model = RandomForestClassifier(n_estimators=10)
tree_model.fit(x_train_dropped, y_train)
importances = tree_model.feature_importances_
selected_features_tree = np.argsort(importances)[-k_best:]
print("Selected features using Tree-based Methods:", selected_features_tree)

# # 6. Principal Component Analysis (PCA)
# pca = PCA(n_components=k_best)
# X_train_pca = pca.fit_transform(x_train_dropped)
# selected_features_pca = pca.components_.argsort()[:, -k_best:]
# print("Selected features using Principal Component Analysis (PCA):", selected_features_pca)

from sklearn.feature_selection import mutual_info_classif
# 7. Information Gain and Entropy (SelectKBest with mutual_info_classif)
selector_info_gain = SelectKBest(score_func=mutual_info_classif, k=k_best)
X_train_info_gain = selector_info_gain.fit_transform(x_train_dropped, y_train)
selected_features_info_gain = np.where(selector_info_gain.get_support())[0]

# 8. Feature Importance from Embedded Methods (SelectFromModel)
embed_model = DecisionTreeClassifier()
embed_selector = SelectFromModel(embed_model)
X_train_embed = embed_selector.fit_transform(x_train_dropped, y_train)
selected_features_embed = np.where(embed_selector.get_support())[0]

Selected features using Univariate Feature Selection: [0 4 5 6 9]


In [ ]:
# Display selected features for each method
# print("Selected features using Correlation Analysis:", highly_correlated_features)
print("Univariate Feature Selection:\n", selected_features_univariate)
print("Recursive Feature Elimination (RFE):\n", selected_features_rfe)
print("Tree-based Methods:\n", selected_features_tree)
# print("LASSO Regression:", selected_features_lasso)
print("Principal Component Analysis (PCA): \n", selected_features_pca)
print("Information Gain and Entropy:\n", selected_features_info_gain)
print("Feature Importance from Embedded Methods:\n", selected_features_embed)

In [ ]:
x_train_dropped

In [ ]:
import pandas as pd


# Get feature names from DataFrame columns
feature_names = x_train_dropped.columns

# Display selected features for each method with names
def print_selected_features(method_name, selected_indices):
    valid_indices = [i for i in selected_indices if i < len(feature_names)]
    selected_feature_names = [feature_names[i] for i in valid_indices]
    print(f"Selected features using {method_name}: {selected_feature_names}")

# Call the function for each method
# print_selected_features("Correlation Analysis", highly_correlated_features[0] if len(highly_correlated_features) > 0 else [])
print_selected_features("Univariate Feature Selection", selected_features_univariate)
print_selected_features("Recursive Feature Elimination (RFE)", selected_features_rfe)
print_selected_features("Tree-based Methods", selected_features_tree)
# print_selected_features("LASSO Regression", selected_features_lasso)
print_selected_features("Principal Component Analysis (PCA)", selected_features_pca[0] if len(selected_features_pca) > 0 else [])
print_selected_features("Information Gain and Entropy", selected_features_info_gain)
print_selected_features("Feature Importance from Embedded Methods", selected_features_embed)


Selected features using Univariate Feature Selection: ['Pid', 'Origin', 'Number of business establishments (secondary sector of industry)', 'Number of business establishments (tertiary sector of industry)', 'Number of employees (tertiary sector of industry)']
Selected features using Recursive Feature Elimination (RFE): ['Number of business establishments (secondary sector of industry)', 'Number of employees (secondary sector of industry)', 'Number of business establishments (tertiary sector of industry)', 'Number of employees (tertiary sector of industry)', 'Night Population']
Selected features using Tree-based Methods: ['Night Population', 'Number of business establishments (secondary sector of industry)', 'Number of employees (secondary sector of industry)', 'Number of business establishments (tertiary sector of industry)', 'Number of employees (tertiary sector of industry)']
Selected features using Principal Component Analysis (PCA): ['Number of employees (secondary sector of indust

Cross-validation is a technique used to assess how well a model will generalize to an independent dataset. It helps to ensure that your model is not overfitting to the training data. Here's a general outline of how you can use cross-validation in combination with feature selection and model training:

You can adapt this template to use different classifiers, feature selection methods, and evaluation metrics based on your specific needs. Keep in mind that the number of features selected (n_features_to_select in the example) and other hyperparameters should be fine-tuned based on the characteristics of your dataset.

Remember to replace the RandomForestClassifier and RFE with the classifier and feature selection method you find most suitable for your problem. Adjust the number of splits in the cross-validation (n_splits) based on the size of your dataset.

This will give you an array of accuracy scores for each fold, as well as the mean accuracy across all folds.

In [ ]:
# from sklearn.model_selection import cross_val_score, StratifiedKFold
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.feature_selection import RFE

# # use the model that you finalize
# model = RandomForestClassifier()
# rfe = RFE(model, n_features_to_select=5)

# # Assuming X is your feature matrix and y is your target variable

# # Feature selection using RFE
# X_selected = rfe.fit_transform(x_train_dropped, y_train)

In [ ]:
X_selected = x_train_dropped.iloc[:, [5, 6, 7, 8, 9]]

In [ ]:
from sklearn.model_selection import cross_val_score, StratifiedKFold

# Initialize cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation with the selected features
scores = cross_val_score(model, X_selected, y_train, cv=cv, scoring='accuracy')

print("Cross-Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


Cross-Validation Scores: [1.         0.99996958 0.99993915 1.         1.        ]
Mean Accuracy: 0.9999817462731974


In [ ]:
# Create and train an XGBoost classifier for multiclass classification
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
X_train['Departure_time'] = le.fit_transform(X_train['Departure_time'].astype(str))
X_train['Occupation'] = le.fit_transform(X_train['Occupation'].astype(str))
X_train['City'] = le.fit_transform(X_train['City'].astype(str))
X_train['Trip_type'] = le.fit_transform(X_train['Trip_type'].astype(str))
model = xgb.XGBClassifier(objective="multi:softprob", num_class=1006)  # "multi:softprob" for multiclass
model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import classification_report

# Make predictions on the test set
X_test['Departure_time'] = le.fit_transform(X_test['Departure_time'].astype(str))
X_test['Occupation'] = le.fit_transform(X_test['Occupation'].astype(str))
X_test['City'] = le.fit_transform(X_test['City'].astype(str))
X_test['Trip_type'] = le.fit_transform(X_test['Trip_type'].astype(str))
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate a classification report

# class_names = data.target_names
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)

# Calculate root mean squared error
rmse = np.sqrt(mse)

print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Squared Error: 118272.18132255945
Root Mean Squared Error: 343.9072277847028


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted', zero_division=1)
print(f'Precision: {precision:.2f}')

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted', zero_division=1)
print(f'Recall: {recall:.2f}')

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted', zero_division=1)
print(f'F1 Score: {f1:.2f}')

# Display classification report
# print('Classification Report:')
# print(classification_report(y_test, y_pred))

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.25
Precision: 0.93
Recall: 0.25
F1 Score: 0.21
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# FOR REFERENCE OF HYPER PARAMETER TUNNING.

import xgboost as xgb
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for grid search
param_grid = {
    'learning_rate': [0.01, 0.1, 0.3],
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'min_child_weight': [1, 2, 3],
    'gamma': [0, 0.1, 0.2],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0]
}


# Create an XGBoost classifier
model = xgb.XGBClassifier(objective="multi:softprob", num_class=1009)

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=5, verbose=1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Train a model with the best hyperparameters
best_model = xgb.XGBClassifier(objective="multi:softprob", num_class=3, **best_params)
best_model.fit(X_train, y_train)

# Make predictions and evaluate the model
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy with Best Hyperparameters:", accuracy)


In [ ]:
# Import the necessary libraries
import xgboost as xgb
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Load the Iris dataset
data = load_iris()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target  # Multiclass classification

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train an XGBoost classifier for multiclass classification
model = xgb.XGBClassifier(objective="multi:softprob", num_class=3)  # "multi:softprob" for multiclass
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate a classification report
class_names = data.target_names
report = classification_report(y_test, y_pred, target_names=class_names)
print("Classification Report:\n", report)

In [ ]:
y

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create scatter plots for three pairs of features
plt.figure(figsize=(12, 6))

headval = 500000

plt.subplot(1, 3, 1)
plt.title("Chukyo City\nDeparture Time vs Night Population")
sns.scatterplot(data=chukyo_modified.head(headval), x="Departure_time", y="Night Population", hue="Destination")

plt.show()

In [ ]:
plt.subplot(1, 2, 1)
plt.title("Tokyo City\nDeparture Time vs Night Population")
sns.scatterplot(data=tokyo_modified.head(headval), x="Departure_time", y="Night Population", hue="Destination")

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create scatter plots for three pairs of features
plt.figure(figsize=(12, 6))

headval = 500000

plt.subplot(1, 3, 1)
sns.scatterplot(data=tokyo_modified.head(headval), x="Age", y="Trip_Encoded", hue="Destination")
plt.title("Occupation vs Night Population")


plt.subplot(1, 3, 2)
sns.scatterplot(data=tokyo_modified.head(headval), x="Age", y="Night Population", hue="Destination")
plt.title("Age vs Night Population")


plt.subplot(1, 3, 3)
sns.scatterplot(data=tokyo_modified.head(headval), x="Gender", y="Night Population", hue="Destination")
plt.title("Gender vs Night Population")

# plt.tight_layout()

# Show the plots
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

plot_data = pd.DataFrame(chukyo_modified)
plt.figure(figsize=(24, 12))

# plt.subplot(1, 1, 1)
bp = sns.histplot(x="Age", y="Occupation", data=plot_data)
bp.set_xticklabels(bp.get_xticklabels(), rotation=45, ha="right")
# plt.title("Night Population Distribution by Trip Type at Hour 1")
plt.xlabel("Age")
plt.ylabel("Occupation")

plt.show()

# plt.subplot(2, 1, 1)
bp = sns.histplot(x="Departure_time", y="Occupation", data=chukyo_modified)
# bp.set_xticklabels(bp.get_xticklabels(), rotation=45, ha="right")
plt.xlabel("Age")
plt.ylabel("Occupation")
plt.show()

# plt.subplot(3, 1, 1)
bp = sns.histplot(x="Departure_time", y="Trip_type", data=plot_data)
# bp.set_xticklabels(bp.get_xticklabels(), rotation=45, ha="right")
plt.title("Night Population Distribution by Trip Type at Hour 1")
plt.xlabel("Departure_time")
plt.ylabel("Trip type")

plt.show()

In [ ]:
temp = chukyo_modified.rename(columns={'Number of business establishments (secondary sector of industry)': 'No. of II sector business.'}, inplace=False)
temp = temp.rename(columns={'Number of employees (secondary sector of industry)': 'Employees in II business'}, inplace=False)
temp = temp.rename(columns={'Number of business establishments (tertiary sector of industry)': 'No. of III sector business.'}, inplace=False)
temp = temp.rename(columns={'Number of employees (tertiary sector of industry)': 'Employees in III business'}, inplace=False)

In [ ]:
temp['Departure_time'] = pd.to_datetime(chukyo_modified['Departure_time'])


temp['Departure_time'] = temp['Departure_time'].dt.hour

# temp['Departure_time'] = temp['Departure_time'].dt.hour

In [ ]:
correlation_matrix1 = temp.corr()
plt.title("Chukyo City\n HeatMap of Correlation Matrix")
sns.heatmap(correlation_matrix1, annot=False, cmap="coolwarm")